#pragma once
enum TybBytovejJednotky {
	BYTY_V_BUDOVACH_S_JEDNYM_BYTOM,
	BYTY_V_BUDOVACH_S_DVOMA_BYTMI,
	BYTY_V_BUDOVACH_S_TROMA_ALEBO_VIAC_BYTMI,
	BYTY_V_NEBYTOVYCH_BUDOVACH,
	NEZISTENE,

	NEDEFINOVANY
};